### ISSUE TITLE
Should we automate collation of i18n assets + integrate with Smartling?

### ISSUE THREAD

**Issue by jnwng** [solana-mobile/app-publishing-spec#12]
i suspect that many teams will forgo the choice to internationalize properly given the choice to skip it. given the ability to automate this process, i think it should be a part of the publishing flow that at least collates the relevant information to submit to an API-based service like Smartling

due to the immutability of releases, this step may need to happen well ahead of publishing time. i'd be willing to make create releases that are mutable but where an entity we control retains update authority for the sole purpose of reconciling internationalization updates automatically with releases

**Comment by creativedrewy** [comment]
Closing as out of scope for now. Will re-integrate into deliverables if desired by partners.
