### ISSUE TITLE
The default locale needs to be interpreted and included in the list of supported locales

### ISSUE THREAD

**Issue by sdlaver** [solana-mobile/app-publishing-spec#122]
By default, the `aapt2 dump badging` output includes an identifier, `--_--`, representing the default locale:
```
$ aapt2 dump badging app-debug.apk
locales: '--_--' 'es'
```

The Android tools assume that the default locale is `en`/`en_US`. For eg:
```
resConfigs("en", "es")
...
locales: '--_--' 'es'
```
```
resConfigs("es", "en")
...
locales: '--_--' 'es'
```
```
resConfigs("es")
...
locales: '--_--' 'es'
```
```
resConfigs("en_GB", "es")
...
locales: '--_--' 'en_GB' 'es'
```
```
resConfigs("en_US", "es")
...
locales: '--_--' 'es'
```

To match the default expectation, the `dapp-store` CLI should assume the default language is `en`. We should also add a field to `config.yaml` that allows overriding this default with another language.

For reference, here is where the `--_--` locale is stripped from the list of supported locales by the `dapp-store` CLI: https://github.com/solana-mobile/app-publishing-spec/blob/35e0a6d669e15a9f2fd912f1835e60b25a47b47b/packages/cli/src/utils.ts#L170

**Comment by creativedrewy** [comment]
Fixed
