### ISSUE TITLE
Finalize "verification" source-of-truth

### ISSUE THREAD

**Issue by jnwng** [solana-mobile/app-publishing-spec#5]
i think it is pretty clear that we should have an out-of-band app verification flow, ideally supported by Hubspot. however, we do need to make a decision on how we surface that information into the Dapp store itself—how do we signal our "acceptance" of a particular published release? a few options for your perusal:

## Entirely off-chain
have the GraphQL API that powers the Dapp Store join release address against acceptance status in HubSpot
**pros**
- easiest to implement

**cons**
- external consumers rely on the GraphQL API as the source-of-truth

## Entirely on-chain
have a designated keypair "sign" the release NFT
**pros**
- easiest for external consumers; all information available on-chain without the use of GraphQL
- can add on-chain "notes" as part of the review process

**cons**
- rabbithole of corner-cases related to keypair management and maintenance
- limited amount of space on the NFT metadata creators array

## Right in the middle
issue a well-formed transaction with a designated keypair

**pros**
- doesn't mess with release NFTs
- retains the ability to add "notes" or other metadata to the review process

**cons**
- operationally, slightly difficult to query for specific transactions and map them to releases

**Comment by creativedrewy** [comment]
Closing as we have adopted the off-chain model.
